### ISSUE TITLE
Getting 401 error

### ISSUE THREAD

**Issue by skruzic** [cotter-code/flask-todolist-api#1]
This API is not working for me. I am getting a 401 error when trying to login, after successful login with cotter.

I followed the [tutorial](https://dev.to/cotter/how-to-make-an-interactive-todo-list-cli-using-python-with-an-easy-login-mechanism-595h?fbclid=IwAR2u49d6ju5XXWRfEEzcrtElmbdtHke4rTsDSfa_KUWHrNua0sEI4mjCv5I), but it seems that the API cannot parse my token.

Here is my code: 
```python
port = 8080
response = cotter.login_with_email_link(api_key, port)

url = 'https://cottertodolist.herokuapp.com/login_register'
headers = {'Content-Type': 'application/json'}
data = response
resp = requests.post(url, json=data, headers=headers)

if resp.status_code != 200:
    resp.raise_for_status()

click.echo(resp.json())
```

**Comment by putrikarunia** [comment]
@skruzic Thanks for catching the error, fixed in 4b4d38ef07de80940755ec70fe495c74aafe86d1. It is updated on heroku as well.

**Comment by putrikarunia** [comment]
@skruzic If it's working for you I'll close the issue.

**Comment by skruzic** [comment]
It seems that it is working now. Thanks!
